version: '3.8'

services:
  siga:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "9010:8000"
    volumes:
      - ./storage:/app/../storage
      - siga_db:/app/db
    environment:
      - DEBUG=1
    restart: unless-stopped

volumes:
  siga_db:
